version: '3.1'

services:

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
      - "15672:15672"
    volumes:
      - ./rabbitmq-data:/bitnami/rabbitmq/mnesia

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo_data:/data/db

  lab:
    image: test-image-name
    build: .
    restart: always
    environment:
      MONGO_URL: "mongodb://root:example@mongo:27017"
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config:/etc/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana